version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: expenses
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
